// Generic loader for the pack ABI. Every pack exports the same four
// functions, so this one file talks to all packs, present and future
// (including packs written in languages other than Rust).
//
// Framing (mirrors crates/core/src/abi.rs):
//   [u32 LE header length][header JSON][payload bytes]

// The pinned pack hashes are imported at build time, so they live inside
// the content-hashed app bundle and are atomically versioned with the
// code that checks them — a runtime-fetched copy could come from a
// different deploy than the app (stale service-worker cache) and fail
// spuriously. Generated by scripts/build-web-assets.sh.
import pins from "./wasm-integrity.json";

const encoder = new TextEncoder();
const decoder = new TextDecoder();

/** module name -> Promise<exports>, so each pack is fetched at most once. */
const packs = new Map();

function toHex(buffer) {
    return Array.from(new Uint8Array(buffer))
        .map((b) => b.toString(16).padStart(2, "0"))
        .join("");
}

async function fetchPack(module, bypassCache) {
    const r = await fetch(`wasm/${module}`, bypassCache ? { cache: "reload" } : undefined);
    if (!r.ok) throw new Error(`failed to fetch pack ${module}`);
    return new Uint8Array(await r.arrayBuffer());
}

// Verify a pack against its pinned sha256 before we ever instantiate it.
// The bytes come from our own origin, but this closes the gap between "the
// server we deployed" and "the code that got compiled and reviewed": a
// tampered or stale pack is refused rather than run. Requires a secure
// context (crypto.subtle) — always true on the deployed https site.
//
// A mismatch is not necessarily tampering: right after a deploy the
// service worker can serve a pack cached from an older deploy than this
// app version. Retry once with the caches bypassed before failing.
async function loadVerified(module) {
    const expected = pins[module];
    if (!expected) throw new Error(`no pinned hash for pack ${module}`);
    let bytes = await fetchPack(module, false);
    if (toHex(await crypto.subtle.digest("SHA-256", bytes)) !== expected) {
        bytes = await fetchPack(module, true);
        const actual = toHex(await crypto.subtle.digest("SHA-256", bytes));
        if (actual !== expected) {
            throw new Error(
                `integrity check failed for ${module}: expected ${expected}, got ${actual}` +
                    " — reloading the page usually fixes this; a failure that" +
                    " persists across reloads means the pack really doesn't match its pin",
            );
        }
    }
    const result = await WebAssembly.instantiate(bytes, {});
    return result.instance.exports;
}

export function loadPack(module) {
    if (!packs.has(module)) {
        // Failures are not memoized: a transient fetch error should not
        // poison the pack for the rest of the session.
        const loading = loadVerified(module).catch((e) => {
            packs.delete(module);
            throw e;
        });
        packs.set(module, loading);
    }
    return packs.get(module);
}

function frame(header, payload) {
    const headerBytes = encoder.encode(JSON.stringify(header));
    const buf = new Uint8Array(4 + headerBytes.length + payload.length);
    new DataView(buf.buffer).setUint32(0, headerBytes.length, true);
    buf.set(headerBytes, 4);
    buf.set(payload, 4 + headerBytes.length);
    return buf;
}

function unframe(buf) {
    const headerLen = new DataView(buf.buffer, buf.byteOffset, 4).getUint32(0, true);
    const header = JSON.parse(decoder.decode(buf.subarray(4, 4 + headerLen)));
    const payload = buf.subarray(4 + headerLen).slice();
    return { header, payload };
}

/** Copy a (ptr << 32 | len)-packed buffer out of wasm memory and free it. */
function takeBuffer(exports, packed) {
    const ptr = Number(packed >> 32n);
    const len = Number(packed & 0xffffffffn);
    const bytes = new Uint8Array(exports.memory.buffer, ptr, len).slice();
    exports.tk_dealloc(ptr, len);
    return bytes;
}

/**
 * Run one tool in a pack.
 * @param {string} module - pack module file, e.g. "text.wasm"
 * @param {string} tool - tool name, e.g. "base64-decode"
 * @param {object} options - option values
 * @param {Object.<string, object|object[]>} inputs - per input port: a
 *   {type, bytes, format?} value, or an ordered array of them (multi ports)
 * @returns the output value in the same shape
 * @throws Error with the tool's message on failure
 */
export async function runTool(module, tool, options, inputs) {
    const exports = await loadPack(module);
    const entries = Object.entries(inputs).flatMap(([port, v]) =>
        (Array.isArray(v) ? v : [v]).map((value) => [port, value]),
    );
    const requestHeader = {
        tool,
        options,
        inputs: entries.map(([port, value]) => {
            const meta = { port, type: value.type, len: value.bytes.length };
            if (value.format) meta.format = value.format;
            return meta;
        }),
    };
    const total = entries.reduce((n, [, v]) => n + v.bytes.length, 0);
    const requestPayload = new Uint8Array(total);
    let offset = 0;
    for (const [, value] of entries) {
        requestPayload.set(value.bytes, offset);
        offset += value.bytes.length;
    }
    const request = frame(requestHeader, requestPayload);

    const ptr = exports.tk_alloc(request.length);
    new Uint8Array(exports.memory.buffer, ptr, request.length).set(request);
    const packed = exports.tk_run(ptr, request.length);
    exports.tk_dealloc(ptr, request.length);

    const { header, payload } = unframe(takeBuffer(exports, packed));
    if (!header.ok) throw new Error(header.error ?? "tool failed");
    return { type: header.output.type, format: header.output.format, bytes: payload };
}

/** Read a pack's own manifest list (mainly useful for debugging/audit). */
export async function packManifests(module) {
    const exports = await loadPack(module);
    const bytes = takeBuffer(exports, exports.tk_manifests());
    return JSON.parse(decoder.decode(bytes));
}

// ---- streaming sessions ----

function callFramed(exports, invoke, request) {
    const ptr = exports.tk_alloc(request.length);
    new Uint8Array(exports.memory.buffer, ptr, request.length).set(request);
    const packed = invoke(ptr, request.length);
    exports.tk_dealloc(ptr, request.length);
    const { header, payload } = unframe(takeBuffer(exports, packed));
    if (!header.ok) throw new Error(header.error ?? "tool failed");
    return { header, payload };
}

/**
 * Open a streaming session for a tool (manifest.streaming must be true).
 * Chunks are tagged with the input port and value index they belong to.
 * Returns { update, endInput, finish, abort }.
 */
export async function openToolStream(module, tool, options) {
    const exports = await loadPack(module);
    const { header } = callFramed(
        exports,
        (p, l) => exports.tk_stream_open(p, l),
        frame({ tool, options }, new Uint8Array(0)),
    );
    const handle = header.handle;
    let live = true;
    return {
        update(port, index, chunk) {
            const { payload } = callFramed(
                exports,
                (p, l) => exports.tk_stream_update(handle, p, l),
                frame({ port, index }, chunk),
            );
            return payload;
        },
        endInput(port, index) {
            const { payload } = callFramed(
                exports,
                (p, l) => exports.tk_stream_end_input(handle, p, l),
                frame({ port, index }, new Uint8Array(0)),
            );
            return payload;
        },
        finish() {
            live = false;
            const { header: h, payload } = unframe(
                takeBuffer(exports, exports.tk_stream_finish(handle)),
            );
            if (!h.ok) throw new Error(h.error ?? "tool failed");
            return payload;
        },
        abort() {
            if (live) exports.tk_stream_abort(handle);
            live = false;
        },
    };
}
