# Generated by scripts/update-packaging.py — do not edit by hand.
# Install:  brew tap koundinyagoparaju/toolkit https://github.com/koundinyagoparaju/toolkit
#           brew install koundinyagoparaju/toolkit/toolkit
class Toolkit < Formula
  desc "Everyday data tools that run entirely on your device"
  homepage "https://koundinyagoparaju.github.io/toolkit/"
  version "0.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koundinyagoparaju/toolkit/releases/download/v0.8.0/toolkit-macos-aarch64.tar.gz"
      sha256 "79fcad0b27a6a281a9b3e551905380509ba22bc593ccf1c76c32b5a062c28614"
    else
      url "https://github.com/koundinyagoparaju/toolkit/releases/download/v0.8.0/toolkit-macos-x86_64.tar.gz"
      sha256 "114fb032c717bef925ac6c4f385ce9a34e4f20633b9267a8a61968078aa90201"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/koundinyagoparaju/toolkit/releases/download/v0.8.0/toolkit-linux-aarch64.tar.gz"
      sha256 "88013ef6e9c2d0bc3e9ba1a9fe543b2b35fcec5578022664340a4f3220fe9dff"
    else
      url "https://github.com/koundinyagoparaju/toolkit/releases/download/v0.8.0/toolkit-linux-x86_64.tar.gz"
      sha256 "b31568004bedfa23999d08198a750f2780bb2c25ba05b7fb877277f633a30c31"
    end
  end

  def install
    bin.install "toolkit"
  end

  test do
    assert_equal "aGk=", shell_output("#{bin}/toolkit run base64-encode hi").strip
  end
end
