# Generated by scripts/update-packaging.py — do not edit by hand.
# Install:  brew tap koundinyagoparaju/toolkit https://github.com/koundinyagoparaju/toolkit
#           brew install koundinyagoparaju/toolkit/toolkit
class Toolkit < Formula
  desc "Everyday data tools that run entirely on your device"
  homepage "https://koundinyagoparaju.github.io/toolkit/"
  version "0.11.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koundinyagoparaju/toolkit/releases/download/v0.11.0/toolkit-macos-aarch64.tar.gz"
      sha256 "afc96fc1c2691bdceb30213cd174c64baf78f6f986da06c177501a5a6951c827"
    else
      url "https://github.com/koundinyagoparaju/toolkit/releases/download/v0.11.0/toolkit-macos-x86_64.tar.gz"
      sha256 "61f7f9eaa0677b5cbfcf3b15adae09bdfdca8431318e9dd566e5346422254bda"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/koundinyagoparaju/toolkit/releases/download/v0.11.0/toolkit-linux-aarch64.tar.gz"
      sha256 "d363d6e9c185a0ce3e253f511ecd7d734567528c78b5a43ab9fb15de5a25d0d7"
    else
      url "https://github.com/koundinyagoparaju/toolkit/releases/download/v0.11.0/toolkit-linux-x86_64.tar.gz"
      sha256 "9f35a97141fe397e48374654211b4ae75f258c59059e20e09e6d9fa2c3b84a2e"
    end
  end

  def install
    bin.install "toolkit"
  end

  test do
    assert_equal "aGk=", shell_output("#{bin}/toolkit run-tool base64-encode hi").strip
  end
end
