# Generated by scripts/update-packaging.py — do not edit by hand.
# Install:  brew tap koundinyagoparaju/toolkit https://github.com/koundinyagoparaju/toolkit
#           brew install koundinyagoparaju/toolkit/toolkit
class Toolkit < Formula
  desc "Everyday data tools that run entirely on your device"
  homepage "https://koundinyagoparaju.github.io/toolkit/"
  version "0.13.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koundinyagoparaju/toolkit/releases/download/v0.13.0/toolkit-macos-aarch64.tar.gz"
      sha256 "6a307eab2e14046b7b342ed56d0a68d8467f3eda243d0cdf1138aa7ab51f56f6"
    else
      url "https://github.com/koundinyagoparaju/toolkit/releases/download/v0.13.0/toolkit-macos-x86_64.tar.gz"
      sha256 "89779ae497aa999a27c6f02c7173c7b3df934da44f4eac8266b080d15a8dc8df"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/koundinyagoparaju/toolkit/releases/download/v0.13.0/toolkit-linux-aarch64.tar.gz"
      sha256 "301664dcd900709f7860064321f6f56dd2040109a6575735aa00fbef52ad650f"
    else
      url "https://github.com/koundinyagoparaju/toolkit/releases/download/v0.13.0/toolkit-linux-x86_64.tar.gz"
      sha256 "85b5dfcaa2e9344cacb9f8eb5a3932a30f27c1f055324842d596ab9017f517a6"
    end
  end

  def install
    bin.install "toolkit"
  end

  test do
    assert_equal "aGk=", shell_output("#{bin}/toolkit run-tool base64-encode hi").strip
  end
end
