#!/usr/bin/env python3
"""Regenerate the Homebrew formula and Scoop manifest for a release.

    update-packaging.py <tag> <path-to-SHA256SUMS> [repo-root]

Run by release.yml after publishing a release, so Formula/toolkit.rb and
bucket/toolkit.json always point at the latest tag with its real hashes.
The files are fully generated — edit the templates here, not the output.
"""

import sys
from pathlib import Path

REPO = "koundinyagoparaju/toolkit"
HOMEPAGE = "https://koundinyagoparaju.github.io/toolkit/"
DESC = "Everyday data tools that run entirely on your device"

FORMULA = """\
# Generated by scripts/update-packaging.py — do not edit by hand.
# Install:  brew tap {repo_owner}/toolkit https://github.com/{repo}
#           brew install {repo_owner}/toolkit/toolkit
class Toolkit < Formula
  desc "{desc}"
  homepage "{homepage}"
  version "{version}"
  license "Apache-2.0"

  base = "https://github.com/{repo}/releases/download/v{version}"

  on_macos do
    if Hardware::CPU.arm?
      url "#{{base}}/toolkit-macos-aarch64.tar.gz"
      sha256 "{macos_arm}"
    else
      url "#{{base}}/toolkit-macos-x86_64.tar.gz"
      sha256 "{macos_x86}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "#{{base}}/toolkit-linux-aarch64.tar.gz"
      sha256 "{linux_arm}"
    else
      url "#{{base}}/toolkit-linux-x86_64.tar.gz"
      sha256 "{linux_x86}"
    end
  end

  def install
    bin.install "toolkit"
  end

  test do
    assert_equal "aGk=", shell_output("#{{bin}}/toolkit run base64-encode hi").strip
  end
end
"""

SCOOP = """\
{{
    "version": "{version}",
    "description": "{desc}",
    "homepage": "{homepage}",
    "license": "Apache-2.0",
    "architecture": {{
        "64bit": {{
            "url": "https://github.com/{repo}/releases/download/v{version}/toolkit-windows-x86_64.zip",
            "hash": "{windows_x86}"
        }}
    }},
    "bin": "toolkit.exe",
    "checkver": {{
        "github": "https://github.com/{repo}"
    }},
    "autoupdate": {{
        "architecture": {{
            "64bit": {{
                "url": "https://github.com/{repo}/releases/download/v$version/toolkit-windows-x86_64.zip"
            }}
        }}
    }}
}}
"""


def main() -> None:
    tag, sums_path = sys.argv[1], sys.argv[2]
    root = Path(sys.argv[3]) if len(sys.argv) > 3 else Path(__file__).resolve().parent.parent
    version = tag.removeprefix("v")

    sums = {}
    for line in Path(sums_path).read_text().splitlines():
        digest, name = line.split()
        sums[name] = digest

    if len(set(sums.values())) != len(sums):
        sys.exit("duplicate hashes in SHA256SUMS — refusing to publish packaging for broken assets")

    fields = {
        "repo": REPO,
        "repo_owner": REPO.split("/")[0],
        "homepage": HOMEPAGE,
        "desc": DESC,
        "version": version,
        "macos_arm": sums["toolkit-macos-aarch64.tar.gz"],
        "macos_x86": sums["toolkit-macos-x86_64.tar.gz"],
        "linux_arm": sums["toolkit-linux-aarch64.tar.gz"],
        "linux_x86": sums["toolkit-linux-x86_64.tar.gz"],
        "windows_x86": sums["toolkit-windows-x86_64.zip"],
    }

    (root / "Formula").mkdir(exist_ok=True)
    (root / "Formula" / "toolkit.rb").write_text(FORMULA.format(**fields))
    (root / "bucket").mkdir(exist_ok=True)
    (root / "bucket" / "toolkit.json").write_text(SCOOP.format(**fields))
    print(f"packaging updated for {tag}")


if __name__ == "__main__":
    main()
