#!/usr/bin/env bash
# Regenerate the Homebrew formula and Scoop manifest for a release.
#
#     update-packaging.sh <tag> <path-to-SHA256SUMS> [repo-root]
#
# Run by release.yml after publishing a release, so Formula/toolkit.rb and
# bucket/toolkit.json always point at the latest tag with its real hashes.
# The files are fully generated — edit the templates here, not the output.
set -euo pipefail

repo="koundinyagoparaju/toolkit"
homepage="https://koundinyagoparaju.github.io/toolkit/"
desc="Everyday data tools that run entirely on your device"

tag="$1"
sums_path="$2"
root="${3:-$(cd "$(dirname "$0")/.." && pwd)}"
version="${tag#v}"

if [ "$(awk '{print $1}' "$sums_path" | sort | uniq -d | wc -l)" -ne 0 ]; then
  echo "duplicate hashes in SHA256SUMS — refusing to publish packaging for broken assets" >&2
  exit 1
fi

sum_for() {
  awk -v name="$1" '$2 == name {print $1; found=1} END {exit !found}' "$sums_path" ||
    { echo "missing $1 in SHA256SUMS" >&2; exit 1; }
}

macos_arm="$(sum_for toolkit-macos-aarch64.tar.gz)"
macos_x86="$(sum_for toolkit-macos-x86_64.tar.gz)"
linux_arm="$(sum_for toolkit-linux-aarch64.tar.gz)"
linux_x86="$(sum_for toolkit-linux-x86_64.tar.gz)"
windows_x86="$(sum_for toolkit-windows-x86_64.zip)"
repo_owner="${repo%%/*}"

mkdir -p "$root/Formula" "$root/bucket"

cat > "$root/Formula/toolkit.rb" <<EOF
# Generated by scripts/update-packaging.sh — do not edit by hand.
# Install:  brew tap $repo_owner/toolkit https://github.com/$repo
#           brew install $repo_owner/toolkit/toolkit
class Toolkit < Formula
  desc "$desc"
  homepage "$homepage"
  version "$version"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/$repo/releases/download/v$version/toolkit-macos-aarch64.tar.gz"
      sha256 "$macos_arm"
    else
      url "https://github.com/$repo/releases/download/v$version/toolkit-macos-x86_64.tar.gz"
      sha256 "$macos_x86"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/$repo/releases/download/v$version/toolkit-linux-aarch64.tar.gz"
      sha256 "$linux_arm"
    else
      url "https://github.com/$repo/releases/download/v$version/toolkit-linux-x86_64.tar.gz"
      sha256 "$linux_x86"
    end
  end

  def install
    bin.install "toolkit"
  end

  test do
    assert_equal "aGk=", shell_output("#{bin}/toolkit run-tool base64-encode hi").strip
  end
end
EOF

cat > "$root/bucket/toolkit.json" <<EOF
{
    "version": "$version",
    "description": "$desc",
    "homepage": "$homepage",
    "license": "Apache-2.0",
    "architecture": {
        "64bit": {
            "url": "https://github.com/$repo/releases/download/v$version/toolkit-windows-x86_64.zip",
            "hash": "$windows_x86"
        }
    },
    "bin": "toolkit.exe",
    "checkver": {
        "github": "https://github.com/$repo"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/$repo/releases/download/v\$version/toolkit-windows-x86_64.zip"
            }
        }
    }
}
EOF

echo "packaging updated for $tag"
