//! The wasm pack ABI.
//!
//! Every pack compiled to `wasm32-unknown-unknown` exports the same four
//! functions (generated by [`export_pack_abi!`]):
//!
//! ```text
//! tk_alloc(len: u32) -> ptr           // caller-owned buffer for the request
//! tk_dealloc(ptr: u32, len: u32)
//! tk_manifests() -> u64               // (ptr << 32 | len) of a JSON manifest array
//! tk_run(ptr: u32, len: u32) -> u64   // (ptr << 32 | len) of a response buffer
//! ```
//!
//! Buffers returned by `tk_manifests`/`tk_run` are owned by the caller and
//! must be released with `tk_dealloc` after copying out.
//!
//! Request and response buffers share one framing:
//!
//! ```text
//! [u32 little-endian header length][header JSON][payload bytes]
//! ```
//!
//! Request header:
//! `{"tool": "...", "options": {...},
//!   "inputs": [{"port": "input", "type": "text", "len": 5}, ...]}`
//! — one entry per input port; the payload section is the ports' raw bytes
//! concatenated in header order, with per-port lengths from `len`.
//!
//! Response header: `{"ok": true, "output": {"type": "..."}}` — payload =
//! output bytes; or `{"ok": false, "error": "..."}` — payload empty.
//!
//! The JS loader implements this same framing in ~50 lines; because it is
//! identical for every pack, one loader serves all packs — and a pack
//! written in any other language just has to speak this framing.

use crate::data::{DataValue, ValueMeta};
use crate::options::Options;
use crate::tool::{run_tool, Inputs, Registry};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
struct RequestHeader {
    tool: String,
    #[serde(default)]
    options: Options,
    inputs: Vec<AbiInput>,
}

#[derive(Serialize, Deserialize)]
struct AbiInput {
    port: String,
    #[serde(flatten)]
    meta: ValueMeta,
    len: u64,
}

#[derive(Serialize, Deserialize)]
struct ResponseHeader {
    ok: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    error: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    output: Option<ValueMeta>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    handle: Option<u32>,
}

#[derive(Serialize, Deserialize)]
struct StreamOpenHeader {
    tool: String,
    #[serde(default)]
    options: Options,
}

#[derive(Serialize, Deserialize)]
struct StreamChunkHeader {
    port: String,
    #[serde(default)]
    index: usize,
}

fn frame(header_json: Vec<u8>, payloads: &[&[u8]]) -> Vec<u8> {
    let total: usize = payloads.iter().map(|p| p.len()).sum();
    let mut buf = Vec::with_capacity(4 + header_json.len() + total);
    buf.extend_from_slice(&(header_json.len() as u32).to_le_bytes());
    buf.extend_from_slice(&header_json);
    for payload in payloads {
        buf.extend_from_slice(payload);
    }
    buf
}

fn unframe(buf: &[u8]) -> Result<(&[u8], &[u8]), String> {
    if buf.len() < 4 {
        return Err("buffer too short for frame header".into());
    }
    let header_len = u32::from_le_bytes(buf[..4].try_into().unwrap()) as usize;
    let rest = &buf[4..];
    if rest.len() < header_len {
        return Err("frame header length exceeds buffer".into());
    }
    Ok((&rest[..header_len], &rest[header_len..]))
}

/// Encode a run request (used by tests and any Rust-side ABI caller; the web
/// loader builds the same bytes in JS). A multi port's values become
/// repeated entries with the same port name; their order is preserved.
pub fn encode_run_request(tool: &str, options: &Options, inputs: Inputs) -> Vec<u8> {
    let mut metas = Vec::new();
    let mut payloads = Vec::new();
    for (port, values) in inputs {
        for value in values {
            let (meta, bytes) = value.into_payload();
            metas.push(AbiInput {
                port: port.clone(),
                meta,
                len: bytes.len() as u64,
            });
            payloads.push(bytes);
        }
    }
    let header = RequestHeader {
        tool: tool.to_string(),
        options: options.clone(),
        inputs: metas,
    };
    let payload_refs: Vec<&[u8]> = payloads.iter().map(Vec::as_slice).collect();
    frame(
        serde_json::to_vec(&header).expect("header serializes"),
        &payload_refs,
    )
}

/// Encode a run response.
pub fn encode_run_response(result: Result<DataValue, String>) -> Vec<u8> {
    match result {
        Ok(value) => {
            let (meta, payload) = value.into_payload();
            let header = ResponseHeader {
                ok: true,
                error: None,
                output: Some(meta),
                handle: None,
            };
            frame(
                serde_json::to_vec(&header).expect("header serializes"),
                &[&payload],
            )
        }
        Err(message) => {
            let header = ResponseHeader {
                ok: false,
                error: Some(message),
                output: None,
                handle: None,
            };
            frame(serde_json::to_vec(&header).expect("header serializes"), &[])
        }
    }
}

/// Decode a run response back into a result (used by tests; the web loader
/// does this in JS).
pub fn decode_run_response(buf: &[u8]) -> Result<DataValue, String> {
    let (header, payload) = unframe(buf)?;
    let header: ResponseHeader =
        serde_json::from_slice(header).map_err(|e| format!("bad response header: {e}"))?;
    if !header.ok {
        return Err(header.error.unwrap_or_else(|| "unknown tool error".into()));
    }
    let meta = header.output.ok_or("response missing output metadata")?;
    DataValue::from_payload(&meta, payload.to_vec())
}

/// Pack-side entry point: decode a request buffer, run the tool against the
/// registry, encode the response. Never panics on malformed input — every
/// failure becomes an error response.
pub fn handle_run(registry: &Registry, request: &[u8]) -> Vec<u8> {
    encode_run_response(run_from_bytes(registry, request))
}

fn run_from_bytes(registry: &Registry, request: &[u8]) -> Result<DataValue, String> {
    let (header, payload) = unframe(request)?;
    let header: RequestHeader =
        serde_json::from_slice(header).map_err(|e| format!("bad request header: {e}"))?;

    let mut inputs = Inputs::new();
    let mut offset: usize = 0;
    for entry in &header.inputs {
        let len = entry.len as usize;
        let end = offset
            .checked_add(len)
            .filter(|&e| e <= payload.len())
            .ok_or("input lengths exceed payload")?;
        let value = DataValue::from_payload(&entry.meta, payload[offset..end].to_vec())?;
        // Repeated port names accumulate in order (multi ports); run_tool
        // rejects multiple values on single ports.
        inputs.entry(entry.port.clone()).or_default().push(value);
        offset = end;
    }

    let tool = registry
        .find(&header.tool)
        .ok_or_else(|| format!("unknown tool \"{}\"", header.tool))?;
    run_tool(tool, inputs, &header.options).map_err(|e| e.message)
}

/// The pack's manifest list as JSON bytes (payload of `tk_manifests`).
pub fn manifests_json(registry: &Registry) -> Vec<u8> {
    serde_json::to_vec(&registry.manifests()).expect("manifests serialize")
}

/// Open a streaming session from a framed request (`{tool, options}`).
pub fn stream_open(
    registry: &Registry,
    request: &[u8],
) -> Result<Box<dyn crate::stream::StreamSession>, String> {
    let (header, _) = unframe(request)?;
    let header: StreamOpenHeader =
        serde_json::from_slice(header).map_err(|e| format!("bad request header: {e}"))?;
    let tool = registry
        .find(&header.tool)
        .ok_or_else(|| format!("unknown tool \"{}\"", header.tool))?;
    crate::stream::open_stream_validated(tool, &header.options)
        .map_err(|e| e.message)?
        .ok_or_else(|| format!("tool \"{}\" does not support streaming", header.tool))
}

/// Decode a framed stream chunk request into (port, index, payload).
pub fn decode_stream_chunk(request: &[u8]) -> Result<(String, usize, &[u8]), String> {
    let (header, payload) = unframe(request)?;
    let header: StreamChunkHeader =
        serde_json::from_slice(header).map_err(|e| format!("bad request header: {e}"))?;
    Ok((header.port, header.index, payload))
}

/// Response carrying a freshly-opened session handle.
pub fn encode_handle_response(handle: u32) -> Vec<u8> {
    let header = ResponseHeader {
        ok: true,
        error: None,
        output: None,
        handle: Some(handle),
    };
    frame(serde_json::to_vec(&header).expect("header serializes"), &[])
}

/// Response carrying emitted stream bytes.
pub fn encode_stream_response(bytes: &[u8]) -> Vec<u8> {
    let header = ResponseHeader {
        ok: true,
        error: None,
        output: None,
        handle: None,
    };
    frame(
        serde_json::to_vec(&header).expect("header serializes"),
        &[bytes],
    )
}

/// Error response (shared by run and stream calls).
pub fn encode_error_response(message: &str) -> Vec<u8> {
    encode_run_response(Err(message.to_string()))
}

/// Generates the wasm ABI exports for a pack. The argument is a function
/// returning the pack's [`Registry`].
///
/// ```ignore
/// toolkit_core::export_pack_abi!(crate::registry);
/// ```
///
/// The exports are only generated for `wasm32` targets so that packs can
/// also be linked natively (CLI) without duplicate-symbol conflicts.
#[macro_export]
macro_rules! export_pack_abi {
    ($registry_fn:path) => {
        #[cfg(target_arch = "wasm32")]
        mod __toolkit_pack_abi {
            fn pack(ptr: *const u8, len: usize) -> u64 {
                ((ptr as u64) << 32) | (len as u64)
            }

            /// Leak a buffer to the caller; released later via `tk_dealloc`.
            fn give(buf: Vec<u8>) -> u64 {
                let boxed = buf.into_boxed_slice();
                let len = boxed.len();
                let ptr = Box::into_raw(boxed) as *const u8;
                pack(ptr, len)
            }

            #[no_mangle]
            pub extern "C" fn tk_alloc(len: u32) -> *mut u8 {
                let mut buf = Vec::<u8>::with_capacity(len as usize);
                let ptr = buf.as_mut_ptr();
                core::mem::forget(buf);
                ptr
            }

            #[no_mangle]
            pub unsafe extern "C" fn tk_dealloc(ptr: *mut u8, len: u32) {
                drop(Vec::from_raw_parts(ptr, len as usize, len as usize));
            }

            #[no_mangle]
            pub extern "C" fn tk_manifests() -> u64 {
                give($crate::abi::manifests_json(&$registry_fn()))
            }

            #[no_mangle]
            pub unsafe extern "C" fn tk_run(ptr: *const u8, len: u32) -> u64 {
                let request = core::slice::from_raw_parts(ptr, len as usize);
                give($crate::abi::handle_run(&$registry_fn(), request))
            }

            // ---- streaming: stateful sessions in a per-pack slab ----

            std::thread_local! {
                static TK_SESSIONS: core::cell::RefCell<
                    Vec<Option<Box<dyn $crate::StreamSession>>>,
                > = core::cell::RefCell::new(Vec::new());
            }

            #[no_mangle]
            pub unsafe extern "C" fn tk_stream_open(ptr: *const u8, len: u32) -> u64 {
                let request = core::slice::from_raw_parts(ptr, len as usize);
                give(match $crate::abi::stream_open(&$registry_fn(), request) {
                    Ok(session) => TK_SESSIONS.with(|slab| {
                        let mut slab = slab.borrow_mut();
                        let handle = slab.iter().position(|s| s.is_none()).unwrap_or_else(|| {
                            slab.push(None);
                            slab.len() - 1
                        });
                        slab[handle] = Some(session);
                        $crate::abi::encode_handle_response(handle as u32)
                    }),
                    Err(e) => $crate::abi::encode_error_response(&e),
                })
            }

            fn with_session(
                handle: u32,
                f: impl FnOnce(
                    &mut Box<dyn $crate::StreamSession>,
                ) -> Result<Vec<u8>, $crate::ToolError>,
            ) -> Vec<u8> {
                TK_SESSIONS.with(|slab| {
                    let mut slab = slab.borrow_mut();
                    match slab.get_mut(handle as usize).and_then(|s| s.as_mut()) {
                        Some(session) => match f(session) {
                            Ok(bytes) => $crate::abi::encode_stream_response(&bytes),
                            Err(e) => {
                                slab[handle as usize] = None; // poisoned
                                $crate::abi::encode_error_response(&e.message)
                            }
                        },
                        None => $crate::abi::encode_error_response("invalid stream handle"),
                    }
                })
            }

            #[no_mangle]
            pub unsafe extern "C" fn tk_stream_update(
                handle: u32,
                ptr: *const u8,
                len: u32,
            ) -> u64 {
                let request = core::slice::from_raw_parts(ptr, len as usize);
                give(match $crate::abi::decode_stream_chunk(request) {
                    Ok((port, index, payload)) => {
                        with_session(handle, |s| s.update(&port, index, payload))
                    }
                    Err(e) => $crate::abi::encode_error_response(&e),
                })
            }

            #[no_mangle]
            pub unsafe extern "C" fn tk_stream_end_input(
                handle: u32,
                ptr: *const u8,
                len: u32,
            ) -> u64 {
                let request = core::slice::from_raw_parts(ptr, len as usize);
                give(match $crate::abi::decode_stream_chunk(request) {
                    Ok((port, index, _)) => with_session(handle, |s| s.end_input(&port, index)),
                    Err(e) => $crate::abi::encode_error_response(&e),
                })
            }

            #[no_mangle]
            pub extern "C" fn tk_stream_finish(handle: u32) -> u64 {
                give(TK_SESSIONS.with(|slab| {
                    let mut slab = slab.borrow_mut();
                    match slab.get_mut(handle as usize).and_then(|s| s.take()) {
                        Some(session) => match session.finish() {
                            Ok(bytes) => $crate::abi::encode_stream_response(&bytes),
                            Err(e) => $crate::abi::encode_error_response(&e.message),
                        },
                        None => $crate::abi::encode_error_response("invalid stream handle"),
                    }
                }))
            }

            #[no_mangle]
            pub extern "C" fn tk_stream_abort(handle: u32) {
                TK_SESSIONS.with(|slab| {
                    if let Some(slot) = slab.borrow_mut().get_mut(handle as usize) {
                        *slot = None;
                    }
                });
            }
        }
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::data::DataType;
    use crate::manifest::{InputSpec, Manifest};
    use crate::tool::{single_input, InputsExt, Tool, ToolError};

    struct Reverse;
    impl Tool for Reverse {
        fn manifest(&self) -> Manifest {
            Manifest {
                name: "reverse".into(),
                label: "Reverse".into(),
                description: String::new(),
                keywords: vec![],
                inputs: InputSpec::sole(DataType::Text),
                output: DataType::Text,
                streaming: false,
                options: vec![],
            }
        }
        fn run(&self, inputs: Inputs, _: &Options) -> Result<DataValue, ToolError> {
            let DataValue::Text(s) = inputs.sole() else {
                unreachable!()
            };
            Ok(DataValue::Text(s.chars().rev().collect()))
        }
    }

    struct Concat;
    impl Tool for Concat {
        fn manifest(&self) -> Manifest {
            Manifest {
                name: "concat".into(),
                label: "Concat".into(),
                description: String::new(),
                keywords: vec![],
                inputs: vec![
                    InputSpec::named("a", DataType::Text),
                    InputSpec::named("b", DataType::Text),
                ],
                output: DataType::Text,
                streaming: false,
                options: vec![],
            }
        }
        fn run(&self, mut inputs: Inputs, _: &Options) -> Result<DataValue, ToolError> {
            let DataValue::Text(a) = inputs.take("a") else {
                unreachable!()
            };
            let DataValue::Text(b) = inputs.take("b") else {
                unreachable!()
            };
            Ok(DataValue::Text(format!("{a}{b}")))
        }
    }

    fn sole_inputs(value: DataValue) -> Inputs {
        single_input(InputSpec::SOLE_NAME, value)
    }

    #[test]
    fn request_response_round_trip() {
        let registry = Registry::new(vec![Box::new(Reverse)]);
        let request = encode_run_request(
            "reverse",
            &Options::new(),
            sole_inputs(DataValue::Text("abc".into())),
        );
        let response = handle_run(&registry, &request);
        assert_eq!(
            decode_run_response(&response).unwrap(),
            DataValue::Text("cba".into())
        );
    }

    #[test]
    fn multi_port_request_round_trip() {
        let registry = Registry::new(vec![Box::new(Concat)]);
        let inputs = Inputs::from([
            ("a".to_string(), vec![DataValue::Text("foo".into())]),
            ("b".to_string(), vec![DataValue::Bytes(b"bar".to_vec())]), // coerced
        ]);
        let request = encode_run_request("concat", &Options::new(), inputs);
        let response = handle_run(&registry, &request);
        assert_eq!(
            decode_run_response(&response).unwrap(),
            DataValue::Text("foobar".into())
        );
    }

    #[test]
    fn unknown_tool_is_error_response_not_panic() {
        let registry = Registry::new(vec![]);
        let request = encode_run_request(
            "nope",
            &Options::new(),
            sole_inputs(DataValue::Text("x".into())),
        );
        let err = decode_run_response(&handle_run(&registry, &request)).unwrap_err();
        assert!(err.contains("unknown tool"));
    }

    #[test]
    fn garbage_request_is_error_response_not_panic() {
        let registry = Registry::new(vec![]);
        assert!(decode_run_response(&handle_run(&registry, &[1, 2, 3])).is_err());
        assert!(decode_run_response(&handle_run(&registry, &[])).is_err());
    }

    #[test]
    fn lying_length_header_is_error_not_panic() {
        let registry = Registry::new(vec![Box::new(Reverse)]);
        // Well-formed frame, but input length exceeds the actual payload.
        let header = br#"{"tool":"reverse","options":{},"inputs":[{"port":"input","type":"text","len":999}]}"#;
        let mut buf = Vec::new();
        buf.extend_from_slice(&(header.len() as u32).to_le_bytes());
        buf.extend_from_slice(header);
        buf.extend_from_slice(b"abc");
        let err = decode_run_response(&handle_run(&registry, &buf)).unwrap_err();
        assert!(err.contains("exceed"), "{err}");
    }
}
